## Final project: Classification with python

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
    <li><a href="https://#Section_1">Instructions</a></li>
    <li><a href="https://#Section_2">About the Data</a></li>
    <li><a href="https://#Section_3">Importing Data </a></li>
    <li><a href="https://#Section_4">Data Preprocessing</a> </li>
    <li><a href="https://#Section_5">One Hot Encoding </a></li>
    <li><a href="https://#Section_6">Train and Test Data Split </a></li>
    <li><a href="https://#Section_7">Train Logistic Regression, KNN, Decision Tree, SVM, and Linear Regression models and return their appropriate accuracy scores</a></li>
</a></li>
</div>
<p>Estimated Time Needed: <strong>180 min</strong></p>
</div>

<hr>


# Instructions


In this notebook, you will  practice all the classification algorithms that we have learned in this course.


Below, is where we are going to use the classification algorithms to create a model based on our training data and evaluate our testing data using evaluation metrics learned in the course.

We will use some of the algorithms taught in the course, specifically:

1. Linear Regression
2. KNN
3. Decision Trees
4. Logistic Regression
5. SVM

We will evaluate our models using:

1.  Accuracy Score
2.  Jaccard Index
3.  F1-Score
4.  LogLoss
5.  Mean Absolute Error
6.  Mean Squared Error
7.  R2-Score

Finally, you will use your models to generate the report at the end. 


# About The Dataset


The original source of the data is Australian Government's Bureau of Meteorology and the latest data can be gathered from [http://www.bom.gov.au/climate/dwo/](http://www.bom.gov.au/climate/dwo/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01).

The dataset to be used has extra columns like 'RainToday' and our target is 'RainTomorrow', which was gathered from the Rattle at [https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData](https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)




This dataset contains observations of weather metrics for each day from 2008 to 2017. The **weatherAUS.csv** dataset includes the following fields:

| Field         | Description                                           | Unit            | Type   |
| ------------- | ----------------------------------------------------- | --------------- | ------ |
| Date          | Date of the Observation in YYYY-MM-DD                 | Date            | object |
| Location      | Location of the Observation                           | Location        | object |
| MinTemp       | Minimum temperature                                   | Celsius         | float  |
| MaxTemp       | Maximum temperature                                   | Celsius         | float  |
| Rainfall      | Amount of rainfall                                    | Millimeters     | float  |
| Evaporation   | Amount of evaporation                                 | Millimeters     | float  |
| Sunshine      | Amount of bright sunshine                             | hours           | float  |
| WindGustDir   | Direction of the strongest gust                       | Compass Points  | object |
| WindGustSpeed | Speed of the strongest gust                           | Kilometers/Hour | object |
| WindDir9am    | Wind direction averaged of 10 minutes prior to 9am    | Compass Points  | object |
| WindDir3pm    | Wind direction averaged of 10 minutes prior to 3pm    | Compass Points  | object |
| WindSpeed9am  | Wind speed averaged of 10 minutes prior to 9am        | Kilometers/Hour | float  |
| WindSpeed3pm  | Wind speed averaged of 10 minutes prior to 3pm        | Kilometers/Hour | float  |
| Humidity9am   | Humidity at 9am                                       | Percent         | float  |
| Humidity3pm   | Humidity at 3pm                                       | Percent         | float  |
| Pressure9am   | Atmospheric pressure reduced to mean sea level at 9am | Hectopascal     | float  |
| Pressure3pm   | Atmospheric pressure reduced to mean sea level at 3pm | Hectopascal     | float  |
| Cloud9am      | Fraction of the sky obscured by cloud at 9am          | Eights          | float  |
| Cloud3pm      | Fraction of the sky obscured by cloud at 3pm          | Eights          | float  |
| Temp9am       | Temperature at 9am                                    | Celsius         | float  |
| Temp3pm       | Temperature at 3pm                                    | Celsius         | float  |
| RainToday     | If there was rain today                               | Yes/No          | object |
| RainTomorrow  | If there is rain tomorrow                             | Yes/No          | float  |

Column definitions were gathered from [http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml](http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)



## **Import the required libraries**


In [1]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [2]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

### Importing the Dataset


In [3]:
df = pd.read_csv("C://Users//NDUBUISI//Downloads//Weather_Data.csv")
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

### Data Preprocessing


#### One Hot Encoding


First, we need to perform one hot encoding to convert categorical variables to binary variables.


In [4]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

Next, we replace the values of the 'RainTomorrow' column changing them from a categorical column to a binary column. We do not use the `get_dummies` method because we would end up with two columns for 'RainTomorrow' and we do not want, since 'RainTomorrow' is our target.


In [5]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

### Training Data and Test Data


Now, we set our 'features' or x values and our Y or target variable.


In [6]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [7]:
df_sydney_processed = df_sydney_processed.astype(float)

In [8]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']
X = np.asarray(features)


### Linear Regression


#### Q1) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `10`.


In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 10)

#### Q2) Create and train a Linear Regression model called LinearReg using the training data (`x_train`, `y_train`).


In [10]:

LinearReg = LinearRegression()
LinearReg.fit(X_train, Y_train)




LinearRegression()

#### Q3) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [11]:
predictions = LinearReg.predict(X_test)
predictions[0:5]

array([0.13217163, 0.27624512, 0.97789001, 0.28736877, 0.13226318])

#### Q4) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
LinearRegression_MAE = mean_absolute_error(predictions, Y_test)
LinearRegression_MSE = mean_squared_error(predictions, Y_test)
LinearRegression_R2 = r2_score(predictions, Y_test)


#### Q5) Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.


In [13]:
Report = {"Metrics":["MAE","MSE","R2"], "Result": 
    [LinearRegression_MAE, LinearRegression_MSE, LinearRegression_R2]}
pd.DataFrame(Report)

Metrics    Result
0     MAE  0.256337
1     MSE  0.115730
2      R2 -0.385250

### KNN


#### Q6) Create and train a KNN model called KNN using the training data (`x_train`, `y_train`) with the `n_neighbors` parameter set to `4`.


In [14]:
KNN = KNeighborsClassifier(n_neighbors = 4).fit(X_train, Y_train)
KNN

KNeighborsClassifier(n_neighbors=4)

#### Q7) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [15]:
predictions = KNN.predict(X_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

#### Q8) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [16]:
KNN_Accuracy_Score = accuracy_score(predictions, Y_test)
KNN_JaccardIndex = jaccard_score(predictions, Y_test)
KNN_F1_Score = f1_score(predictions, Y_test)

Report_1 = {"metrics":['Acc_Score', 'Jacc_Score', 'F1_Score'], "Result":
         [KNN_Accuracy_Score, KNN_JaccardIndex, KNN_F1_Score]}
pd.DataFrame(Report_1)



metrics    Result
0   Acc_Score  0.818321
1  Jacc_Score  0.425121
2    F1_Score  0.596610

### Decision Tree


#### Q9) Create and train a Decision Tree model called Tree using the training data (`x_train`, `y_train`).


In [17]:
Tree = DecisionTreeClassifier(criterion = 'entropy', max_depth = 3)
Tree

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [18]:
Tree.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

#### Q10) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [19]:
predictions = Tree.predict(X_test)
predictions[0:5]

array([0., 0., 1., 0., 0.])

#### Q11) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [20]:
Tree_Accuracy_Score = accuracy_score(predictions, Y_test)
Tree_JaccardIndex = jaccard_score(predictions, Y_test)
Tree_F1_Score = f1_score(predictions, Y_test)

Report_2 = {"metrics":['Acc_Score', 'Jacc_Score', 'F1_Score'], "Result":
           [Tree_Accuracy_Score, Tree_JaccardIndex, Tree_F1_Score]}
pd.DataFrame(Report_2)

metrics    Result
0   Acc_Score  0.803053
1  Jacc_Score  0.361386
2    F1_Score  0.530909

### Logistic Regression


#### Q12) Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `1`.


In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

#### Q13) Create and train a LogisticRegression model called LR using the training data (`x_train`, `y_train`) with the `solver` parameter set to `liblinear`.


In [22]:
LR = LogisticRegression(C= 0.01, solver = 'liblinear').fit(X_train, Y_train)

#### Q14) Now, use the `predict` and `predict_proba` methods on the testing data (`x_test`) and save it as 2 arrays `predictions` and `predict_proba`.


In [23]:
predictions = LR.predict(X_test)
predictions[0:5]


array([0., 0., 1., 0., 0.])

In [24]:
predict_proba = LR.predict_proba(X_test)
predict_proba[0:5]

array([[0.71865777, 0.28134223],
       [0.97588262, 0.02411738],
       [0.49701196, 0.50298804],
       [0.66413211, 0.33586789],
       [0.97404694, 0.02595306]])

#### Q15) Using the `predictions`, `predict_proba` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [25]:
LR_Accuracy_Score = accuracy_score(predictions, Y_test)
LR_JaccardIndex = jaccard_score(predictions, Y_test)
LR_F1_Score = f1_score(predictions, Y_test)
LR_Log_Loss = log_loss(predictions, Y_test)

Report_3 = {"metrics":['Acc_Score', 'Jacc_Score', 'F1_Score', 'Log_loss'], "Result":
           [LR_Accuracy_Score, LR_JaccardIndex, LR_F1_Score, LR_Log_Loss]}
pd.DataFrame(Report_3)

metrics    Result
0   Acc_Score  0.827481
1  Jacc_Score  0.484018
2    F1_Score  0.652308
3    Log_loss  6.218218

### SVM


#### Q16) Create and train a SVM model called SVM using the training data (`x_train`, `y_train`).


In [26]:
SVM = svm.SVC(kernel = 'rbf')
SVM.fit(X_train, Y_train)

SVC()

#### Q17) Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [27]:
predictions = SVM.predict(X_test)
predictions[0:5]

array([0., 0., 0., 0., 0.])

#### Q18) Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [29]:
SVM_Accuracy_Score = accuracy_score(predictions, Y_test)
SVM_JaccardIndex = jaccard_score(predictions, Y_test)
SVM_F1_Score = f1_score(predictions, Y_test)
Report_4 = {"metrics":['Acc_Score', 'Jacc_Score', 'F1_Score'], "Result":
           [SVM_Accuracy_Score, SVM_JaccardIndex, SVM_F1_Score]}
pd.DataFrame(Report_4)

metrics    Result
0   Acc_Score  0.722137
1  Jacc_Score  0.000000
2    F1_Score  0.000000

### Report


#### Q19) Show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.

\*LogLoss is only for Logistic Regression Model


In [30]:
Report = {"models":[ 'KNN', 'DEC_TREE', 'SVM'], "metrics":['Acc_Score', 'Jacc_Score', 'F1_Score'], "Result":
         [[KNN_Accuracy_Score, KNN_JaccardIndex, KNN_F1_Score], [Tree_Accuracy_Score, Tree_JaccardIndex, Tree_F1_Score], [SVM_Accuracy_Score, SVM_JaccardIndex, SVM_F1_Score]]}
pd.DataFrame(Report)

models     metrics                                             Result
0       KNN   Acc_Score  [0.8183206106870229, 0.4251207729468599, 0.596...
1  DEC_TREE  Jacc_Score  [0.8030534351145038, 0.3613861386138614, 0.530...
2       SVM    F1_Score                     [0.7221374045801526, 0.0, 0.0]